# Generated by Django 3.2.4 on 2023-11-28 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_connection_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
