# Generated by Django 3.2.4 on 2023-12-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_connection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_accounts_connection_following_+', to='accounts.Connection'),
        ),
    ]
